config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get 'galeria/galeria'


  get 'inicio/inicio'

  get 'acercade/acercade'

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles
root :to => "locations#index"

  


  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
    #root 'acercade#acercade', as: 'acercade_acercade', via: :all
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true, length: { minimum: 10 }
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG, or PNG image.'
  }

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_destroy :ensure_an_admin_remains
  validates :name, presence: true, uniqueness: true
  has_secure_password

  class Error < StandardError
  end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
end

app/helpers/acercade_helper.rb
module AcercadeHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<div class="jumbotron text-center">
  <h1>Bienvenidos</h1> 
  <p>En esta pagina podras encontrar los centros deportivos mas atractivos de Dolores Hidalgo
<br>
En la parte izquierda se encuentra un menu donde podras encontrar la ubicacion de los lugares asi como galeria, y podras realizar tus pagos de estos centros deportivos
  </p> 
  
</div>

It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Centros deportivos Dolores Hidalgo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-ckeditor-track': 'reload' %>
    <%= csrf_meta_tags %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      <!--<%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.to_s), onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>-->
      <!--<%= image_tag 'depositphotos_45578761-stock-illustration-logo-pc.jpg', :size => '30x85', alt: 'The Progamatic Bookshelf' %>-->
      <span class="title">"Centros Deportivos Dolores Hidalgos"<%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        <div id="cart">
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>

          <% if session[:user_id] %>
             
              <ul>
                <%= button_to 'Logout', logout_path, method: :delete, class:'btn btn-danger', style:'width:100%' %><br>
                <br>
                
                  <li>
                    <a  href="<%= orders_path%>"><button type="button" class="btn btn-danger" style="width:100%">Lista de Ordenes</button></a>
                  </li>
                  <br>
                   <li>
                    <a  href="<%= products_path%>"><button type="button" class="btn btn-danger" style="width:100%">Pagos de concepto</button></a>
                  </li>
                   <br>
                    <li>
                      <a  href="<%= users_path%>"><button type="button" class="btn btn-danger" style="width:100%">Crear usuarios</button></a>
                    </li>


                
              </ul>
               <br>
                <br>

          <% end %>
        </div>

        
         <ul>

          <li>
            <a  href="<%= admin_path%>"><button type="button" class="btn btn-danger" style="width:100%">Inicio</button></a>
          </li>
           <br>
         <li>
          <a href="<%= locations_path%>"><button type="button" class="btn btn-danger" style="width:100%">Geolocalización</button></a>
        </li>
 <br>
          <li>
            <a href="<%= acercade_acercade_path%>"><button type="button" class="btn btn-danger" style="width:100%">Acerca de</button></a>
          </li>
           <br>
          <li>
            <a href="<%= galeria_galeria_path%>"><button type="button" class="btn btn-danger" style="width:100%">Realidad Aumentada</button></a>
          </li>
           <br>
         <li>
          <a href="<%= login_path%>"><button type="button" class="btn btn-danger" style="width:100%">Login</button></a>
        </li>
         <br>
   <li>
    <a href="/store"><button type="button" class="btn btn-danger" style="width:100%">Compra</button></a>
  </li>
          
        </ul>


      </div>



      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>